[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32u083rctx"

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "trace"

[unstable]
build-std = ["panic_abort", "core"]
build-std-features = ["panic_immediate_abort"]
